name: SOAP-Library

'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        env:
          ROBOT_TESTS_DIR: ${{ github.workspace }}/Tests
          ROBOT_REPORTS_DIR: ${{ github.workspace }}/Tests/Report
        with:
          python-version: '3.10'
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run Robot File
        run: robot -d ./Tests/Report ./Tests/keyword_tests.robot
      - name: Upload test results
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: reports
          path: ${{ github.workspace }}/Tests/Report

  generate_report:
    if: always()
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download reports
        uses: actions/download-artifact@v1
        with:
          name: Robot_reports
      - name: Get Repository Owner & Name
        run: |
          export OWNER="$(echo "${{ github.repository }}" | awk -F / '{print $1}' | sed -e "s/:refs//")"
          export REPO="$(echo "${{ github.repository }}" | awk -F / '{print $2}' | sed -e "s/:refs//")"
      - name: Send report to commit
        uses: Altran-PT-GDC/Robot-Framework-SOAP-Library@v2
        env:
          GH_ACCESS_TOKEN: ${{ secrets.TOKEN }}
          REPO_OWNER: ${{ env.REPOSITORY_OWNER }}
          COMMIT_SHA: ${{ github.sha }}
          REPOSITORY: ${{ env.REPOSITORY_NAME }}
          REPORT_PATH: Tests